language: android
jdk: oraclejdk8

branches:
  only:
    - master

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.1
    - android-26
    - extra-google-m2repository
  licenses:
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo yes | sdkmanager tools
  - echo yes | sdkmanager "system-images;android-24;default;armeabi-v7a"
  - echo no | avdmanager create avd --force -n test -k "system-images;android-24;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

install:
  - ./gradlew clean :library:assemble --stacktrace

before_script:
  - android-wait-for-emulator
  - |
    while ! adb shell getprop init.svc.bootanim; do
      echo Waiting for boot animation to end
      sleep 10
    done
  - |
    while ! adb shell getprop ro.build.version.sdk; do
      echo Waiting for ro.build.version.sdk value from device
      sleep 10
    done
  - adb devices
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v

script:
  - ./gradlew :library:check :library:jacocoTestReport :library:connectedAndroidTest --stacktrace --info

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: ./gradlew clean :library:assembleRelease :library:bintrayUpload -PbintrayUser=$bintray_user -PbintrayKey=$bintray_api_key -PdryRun=false --stacktrace
  on:
    tags: true
    all_branches: true

env:
  global:
    - secure: qI9rc8Kmv5mhGqQFiHaQ4bgFBFOdvo5EQXBp4eutbY7aC26j+3V4sabsE5HX7PUo5/AMlFPqjJ8eRIfKuR3iQEJonrSNSv7X+sxE3PTplT4sHDGnbvjPlUObl+Fm6s9TniaEp9svVzMmUDY+uzu5PvWysdgjF9XFPMAFuJ9tUfExI9c8Cw57eNGxndnKUiu00Y6UHYmMsbr5Ut9DqI3nWk6gCH8yQNcEh92y1S398xX+yVP6cZZkNcpCY8+RqaeA/3POK5n8wBrNDwxIbM169Wa4lljy8lDxo1nc+/aCYazuWuoYyV86y0W/NdZjTpzTIPxEMZARTVJRvLfgGlNZm7xoHjrHBhHFsW7/3gPgS9Y+RCu6cX/LNZcy9/HtWwBcHfHBCeOsNm48etexnx1fKAOAw4my50SHpMM1kVJ4iexEk6BnLX/4SvdTlrhbOXSKDgJosUgUBpbbj4/54+vGEWix3nezyU/AIJwHOPcYQudlnzC0VQBj4NtF/lPAx112JA+sl2n1mBXlVG+k/LjDuEzv+JHvWZNrLWWnPNJXUeaLl3Wg8KuKPyh65Dmp8V+lJgcMt2h2VfvEUTo9clG5q+/JJvbTTdnebTFcxFSAtpSlGEpE2J119tOhsNesxfvGrgj6ZQJJAbbVLwEJqggzxvnCfFlgds+AWunOYM4noqg=
    - secure: rdv+98DWsblJ/zkV5IMRkE3XoSNE4mDBsKTUFYRwsoGqmjnbafq3iE+aDtw+DABis8UnZG17lM/GR5qJ3Gi6ccpIjwyVdy3xpcuDWXxXTNTiradPlQm44Bfav3Uq3eqkODYwoYUsVfoY7jz2aopWkSq3qrbyOGJ7Emwa/o4iIfRXT+7PXDZiyt6VCcYzjRmE0cQrLY1hH3akunuX3hYLm577Xu1FyxMathnppkrPFfF5sxNc+tIFkkBhXSkTqZjfOHccescXeV+ZeZymWmoaSxyzZQ6dK2w7l4T0mMWFeFvcKq/hbaPh9Fgo2oM5wOQk7osOdDUZB1t8t7BIk165T1E4WnFwN95IJdm4+J7NaC2IsubfCXrvbOj1YZ7YfFGjPMLNJ9uw902L32BC0b3wEYJUS8K/KkLwKyw7FqAAeirzLGF3TFm6uDLOLLrTvSdKIUNPbe4G7GVDceYmSd0NFTvm4kqgA69a9giybPz+br1kE8VaQpPHxCbBZbP8WLZpmWZAikgXrVTKJXuIeBjRn842snbpEPsAPy2KVm8N+gHkJKrqFiAUdByzdQItFNoTQFeBPkp7LfPqyiLvtt9QNZ/WFqN5DRZF2W5H0kWJYfdgkFaOaQHwGcBIVOKqDlfGNzM+hK3bkM4t0/uqM6qvs+dsKv6m0n1sBcMuGK9KdLw=

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
